log:
  level: INFO

api:
  insecure: true
  dashboard: true

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"
    tls:

providers:
  docker:
    exposedByDefault: false
    defaultRule: 'Host(`{{ trimPrefix `/` .Name }}.{{ index .Labels "com.docker.compose.project" }}.docker`)'
  file:
    filename: /usr/src/app/dynamic.yml
    watch: true
